[#function collect_connectors  diagramLinks ]
[#local result =[] ]
[#list diagramLinks as diagramLink]
[#if  !(diagramLink.hidden) && !(diagramLink.connector.client.isClassifier) && !(diagramLink.connector.supplier.isClassifier) ]
[#local result = result+[diagramLink.connector] ]
[/#if]
[/#list]
[#return result?sort_by("name")]
[/#function]

[#function show_name element]
[#local name = element.name]
[#if !(element.isClassifier)]
[#local name = element.classifier.name]
[/#if]
[#return name]
[/#function]

[#function collect_component_elements diagram]
[#local temp_hash ={} ]
[#list diagram.diagramObjects as object]
[#if object.element.type == "Component"]
[#local temp_hash = temp_hash+ { object.element.classifier.name : object.element}]
[/#if]
[/#list]
[#local result=[]]
[#list temp_hash?keys?sort as k]
[#local result = result +[temp_hash[k]] ]
[/#list]
[#return result]
[/#function]

[#function show_tag element tag_name]
[#local result = ""]
[#list element.taggedValues as tg]
[#if tg.name == tag_name ]
[#local result = tg.value]
[/#if]
[/#list]
[#return result]
[/#function]